drop table actionlog;
drop table product;
drop table supplier;
drop table login;

CREATE TABLE supplier(
supplier_ID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT pk_supplier_supplierID PRIMARY KEY,
supplier_name VARCHAR2(50) CONSTRAINT nn_supplier_suppliername NOT NULL UNIQUE,
address VARCHAR2(50),
contact VARCHAR2(20),
email VARCHAR2(50)

);


CREATE TABLE product(
product_ID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT pk_product_product_ID  PRIMARY KEY,
product_code VARCHAR2(10) CONSTRAINT nn_product_productcode NOT NULL CONSTRAINT uq_productcode UNIQUE,
product_name VARCHAR2(20) CONSTRAINT nn_product_productname NOT NULL,
description VARCHAR2(40),
cost NUMBER(10,2) CONSTRAINT nn_product_cost NOT NULL,
quantity NUMBER 
      CONSTRAINT nn_product_qty NOT NULL 
      CONSTRAINT check_product_qty CHECK (quantity > 0),
retail_price NUMBER(10,2) CONSTRAINT nn_product_retailprice NOT NULL,
discount NUMBER(4,2),
supplier_ID INT CONSTRAINT fk_product_supplierID REFERENCES supplier(supplier_ID)
);


CREATE TABLE login(
user_ID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) CONSTRAINT pk_login_user_ID PRIMARY KEY,
username VARCHAR2(30) NOT NULL CONSTRAINT uq_username UNIQUE ,
password VARCHAR2(30) CONSTRAINT ck_login_password CHECK(LENGTH(password) BETWEEN 3 AND 30),
user_type VARCHAR2(20) CONSTRAINT nn_login_usertype NOT NULL,
last_logintime DATE DEFAULT SYSDATE 
);

CREATE TABLE actionlog(
user_ID INT CONSTRAINT fk_actionlog_user_id REFERENCES login(user_id),
product_ID INT CONSTRAINT fk_actionlog_productID REFERENCES product(product_ID),
date_modified TIMESTAMP CONSTRAINT nn_actionlog_datemodified NOT NULL
);


INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Iaculis Corp.','8860 Mattis St.','(543) 530-4540','iu@parturientmontesnascetur.co.uk');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Faucibus Orci Bakery','Ap #233-6016 Sapien. St.','(989) 870-3264','faucibus@dolor.net');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Elementum At Incorporated','Ap #885-9440 Vel, St.','(378) 928-9153','elementum.turpis@orci.net');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Sit Amet Dapibus Company','471-9289 Leo, Avenue','(742) 466-5737','sitamet@Proin.co.uk');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Sodales Mauris Blandit Ltd','2700 Natoque Avenue','(872) 515-3900','sodales.mauris.@Integer.org');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Anytime Ltd','9039 Lectus Av.','(201) 946-6017','at@idnunc.com');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Habitant Limited','Ap #623-2276 Phasellus Rd.','(756) 747-4183','habitant@gmail.com');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Euismod Mauris Eu Inc.','P.O. Box 831, 5703 Eget Ave','(625) 859-9751','ultrices.Vivamus@molestieSed.org');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Duis At Lacus Associates','403-4986 Donec Ave','(712) 797-9564','Integer@sed.net');
INSERT INTO supplier (supplier_name,address,contact,email) VALUES ('Interdum Feugiat Sed Associates','Ap #497-9847 Ac Road','(283) 216-2317','interdum@yahoo.com');


INSERT INTO product (product_code,product_name,description,cost,quantity,retail_price,discount,supplier_ID) 
VALUES ('BN2384','brownies','chocolate',5,7800,2,1,1);
INSERT INTO product (product_code,product_name,description,cost,quantity,retail_price,discount,supplier_ID) 
VALUES ('ST6677','shortcake','strawberry',4,10000,3,2,2);
INSERT INTO product (product_code,product_name,description,cost,quantity,retail_price,discount,supplier_ID) 
VALUES ('CK8889','cookie','chocolatechip',4,20000,2,1,3);
INSERT INTO product (product_code,product_name,description,cost,quantity,retail_price,discount,supplier_ID) 
VALUES ('MF7787','muffin','vanilla',5.25,99900,2.25,2,4);
INSERT INTO product (product_code,product_name,description,cost,quantity,retail_price,discount,supplier_ID) 
VALUES ('CR4453','croissant','cheese',6.50,780560,2.50,1,5);

INSERT INTO login(username,password,user_type) VALUES('admin','1234','manager');
INSERT INTO login(username,password,user_type) VALUES('sukhpreet','1234','employee');
select * from login;
commit;
--delete from product where product_ID='5';
select * from product;
select * from supplier;